[package]
name = "qproxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "qproxy"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }